---
# - name: Install hadoop master node
#   hosts: hadoop-master
#   remote_user: hadoop
#   sudo: yes
#
#   roles:
#     - common
#     - oraclejava8
#     - master
#     - spark


  #   - cassandra
  # vars:
  #   cassandra_configuration:
  #     authenticator: PasswordAuthenticator
  #     cluster_name: MyCassandraCluster
  #     commitlog_directory: /data/cassandra/commitlog
  #     commitlog_sync: periodic
  #     commitlog_sync_period_in_ms: 10000
  #     data_file_directories:
  #       - /data/cassandra/data
  #     endpoint_snitch: GossipingPropertyFileSnitch
  #     hints_directory: "/data/cassandra/hints"
  #     listen_address: "{{ ansible_default_ipv4.address }}"
  #     partitioner: org.apache.cassandra.dht.Murmur3Partitioner
  #     saved_caches_directory: /data/cassandra/saved_caches
  #     seed_provider:
  #       - class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
  #         parameters:
  #           - seeds: "{{ ansible_default_ipv4.address }}"
  #     start_native_transport: true
  #
  #   cassandra_configure_apache_repo: true
  #
  #   cassandra_dc: DC1
  #
  #   # Create an alternative directories structure for the Cassandra data.
  #   # In this example, the will be a directory called /data owned by root
  #   # with rwxr-xr-x permissions.  It will have a series of sub-directories
  #   # all of which will be defaulted to being owned by the cassandra user
  #   # with rwx------ permissions.
  #   cassandra_directories:
  #     root:
  #       group: root
  #       mode: "0755"
  #       owner: root
  #       paths:
  #         - /data
  #     data:
  #       paths:
  #         - /data/cassandra
  #         - /data/cassandra/commitlog
  #         - /data/cassandra/data
  #         - /data/cassandra/hints
  #         - /data/cassandra/saved_caches
  #
  #   cassandra_rack: RACK1
  #
  #   cassandra_repo_apache_release: 311x


- name: Install hadoop data nodes
  hosts: hadoop-data
  remote_user: debian
  sudo: yes
  # become: yes
  roles:
    - common
    - oraclejava8
    - spark

   # - common
   # - couch2
   # - yarnEnv

# - name: Install hadoop data nodes
#   hosts: hadoop-master
#   remote_user: hadoop
#   sudo: yes
#   tasks:
#   - name: Ansible copy file force
#     copy:
#       src: yarn-site.xml
#       dest: /home/vagrant/src
#       force: yes


  # vars:
  #   nodejs_version: 0.10.28
  #   nodejs_install_dir: /home/pi/nodejs
  #   rebar_version: 2.5.1
  #   rebar_install_dir: /home/pi/rebar
  #   couchdb_version: developer-preview-2.0
  #   couchdb_install_dir: /home/pi/couchdb
  #
  # tasks:
  #   - include: roles/couch/tasks/install-erlang.yml
  #   - include: roles/couch/tasks/install-nodejs.yml
  #   - include: roles/couch/tasks/install-rebar.yml
  #   - include: roles/couch/tasks/install-couchdb.yml







# --ignore-installed six
